# Generated by Django 5.2 on 2025-04-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0002_delete_fertilizerrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.crop')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.soiltype')),
                ('suitable_fertilizers', models.ManyToManyField(blank=True, to='cemapp.fertilizer')),
            ],
        ),
    ]
