# Generated by Django 5.2 on 2025-04-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0006_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
