# Generated by Django 5.2 on 2025-04-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0008_sale_payment_stockalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='fertilizer',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='fertilizer',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='StockAlert',
        ),
    ]
