# Generated by Django 5.2 on 2025-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0009_remove_sale_customer_remove_sale_fertilizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
