# Generated by Django 5.2 on 2025-04-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0010_fertilizer_minimum_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.fertilizer')),
            ],
        ),
    ]
