# Generated by Django 5.2 on 2025-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='adhar_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='contact_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='farmer_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
