# Generated by Django 5.2 on 2025-04-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0013_sale_address_sale_adhar_number_sale_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='adhar_number',
            new_name='aadhar_number',
        ),
    ]
