# Generated by Django 5.2 on 2025-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0014_rename_adhar_number_sale_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
