# Generated by Django 5.2 on 2025-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0015_fertilizer_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='stock',
        ),
    ]
